## 00. PyTorch Fundamentals


In [1]:
import torch 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.0


## 1. Introduction to Tensors

### Creating tensors

PyTorch tensors are created using `torch.Tensor()`

In [2]:
# scaler
scaler = torch.tensor(7)
scaler

tensor(7)

In [3]:
scaler.ndim

0

In [4]:
# Get tensor back as Python int
scaler.item()

7

In [5]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random tensors

why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [15]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0476, 0.7762, 0.8493, 0.9022],
        [0.3041, 0.8375, 0.4757, 0.1642],
        [0.3365, 0.3441, 0.3990, 0.2874]])

In [16]:
# Create a random tensor with similar shape to an image tesor
random_tensor_size_tensor = torch.rand(size=(224,224,3)) # height, width, color channel (R,G,B)
random_tensor_size_tensor.shape, random_tensor_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [17]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [18]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [19]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [20]:
# Use torch.range()
one_to_ten = torch.arange(start=0,end=11,step=1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
# creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatypte
2. Tensors not right shape
3. Tensors not on the right device

In [22]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=torch.float32,                    # What datatype is the tensor (e.g float32 or float16)
                               device=None,                        # What device is your tensor on
                               requires_grad=False)   # Whether or not to track gradients with this tensor operation
float_32_tensor

tensor([3., 6., 9.])

In [23]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [24]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [25]:
int_32_tensor = torch.tensor([3,6,9],dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [26]:
float_16_tensor*int_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

### Getting information from tensors

1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [27]:
# Create a tensor
some_tensor =torch.rand(3,4)
some_tensor

tensor([[0.4174, 0.4173, 0.5273, 0.2684],
        [0.3020, 0.3288, 0.5193, 0.8731],
        [0.7108, 0.8320, 0.7505, 0.1815]])

In [28]:
# Find out details about some tensor
print(some_tensor)
print(f'Datatype of tensor: {some_tensor.dtype}')
print(f'Shape of tensor: {some_tensor.shape}')
print(f'Device of tensor: {some_tensor.device}')

tensor([[0.4174, 0.4173, 0.5273, 0.2684],
        [0.3020, 0.3288, 0.5193, 0.8731],
        [0.7108, 0.8320, 0.7505, 0.1815]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [29]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [30]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [31]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [32]:
# Try out PyTorch in-built function
torch.mul(tensor,10)

tensor([10, 20, 30])

In [33]:
torch.add(tensor,10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication must satify:

1. The **inner dimensions** must match:
   * `(2,3) @ (2,3) won't work`
   * `(3,2) @ (3,2) won't work`
   * `(2,3) @ (3,2) will work`
   * `(3,2) @ (2,3) will work`
   
3. The resulting matrix has the shape of the **outer dimensions**:
   * `(2,3) @ (3,2) -> (2,2)`
   * `(3,2) @ (2,3) -> (3,3)`

# Element wise multiplication
print(tensor, "*", tensor)
print(f'Equals: {tensor*tensor}')

In [34]:
# Matrix Multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [35]:
tensor

tensor([1, 2, 3])

In [36]:
# Matrix multiplication by hand
1*1 +2*2+3*3

14

In [37]:
%%time
value = 0
for i in range(len(tensor)):
    value+=tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: total: 0 ns
Wall time: 117 ms


In [38]:
%%time
torch.matmul(tensor,tensor)  # tensor @ tensor

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

### One of the most common errors in deep learning: shape errors

In [39]:
# Shape for matrix multiplication
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

# torch.mm(tensor_A,tensor_B) # torch.mm is the same as torc.matmul( it's a alias for )
torch.matmul(tensor_A,tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [40]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a transpose.

A **transpose** switches the axes or dimensionns of a given tensor.

In [43]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [44]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [46]:
# The matrix multiplication operation works when tensor_B is transposed
print(f'Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}')
print(f'New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T={tensor_B.T.shape}')
print(f'Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimentsionns must match')
print('Output:\n')
output = torch.mm(tensor_A,tensor_B.T)
print(output)
print(f'\noutput shape: {output.shape}')

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T=torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimentsionns must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum etc (tesor aggregation)

In [51]:
# Create a tesor
x = torch.arange(0,100,10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [48]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [49]:
# Find max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [54]:
# Find the mean - note: thhe torch.mean() function requries a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [57]:
# Find the sum
torch.sum(x), sum(x),x.sum()

(tensor(450), tensor(450), tensor(450))

### Find the positional min and max

In [61]:
# Find the position in tensor that has the maximum value with ArgMax
torch.argmax(x), x.argmax()

(tensor(9), tensor(9))

In [63]:
# Find the position in tensor that has the minimum value with ArgMin
torch.argmin(x), x.argmin()

(tensor(0), tensor(0))

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the orginal tensor
* Stacking -- combine multiple tensors on top of each other(vstack) or side by side (hstack)
* Squeeze - remmoves all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute- Return a view of the input with dimensions permuted (swapped) in a certain way

In [70]:
# Let's create a tensor
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [71]:
# Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [73]:
# Change the view
z = x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [74]:
# changing z changes x (because a view of a tensor shares the same memory as the original inputs )
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [79]:
# stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [85]:
# torch.squeeze() - remove all single dimensions from a target tensor
print(f'Previous tensor: {x_reshaped}')
print(f'Previous shape: {x_reshaped.shape}')

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f'\nNew tensor: {x_squeezed}')
print(f'New shape: {x_squeezed.shape}')

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [87]:
# torch.unsqueez() - adds a single dimension to a target tensor at a specific dim (dimensions))
print(f'Previous target: {x_squeezed}')
print(f'Previous shape: {x_squeezed.shape}')

# Add an extra dimension with usqeezed
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f'\nNew tensor: {x_unsqueezed}')
print(f'New shape: {x_unsqueezed.shape}')

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [92]:
# torch.permute - rearranges the dimensions of target tensors in a specific order
x_original = torch.rand(size=(224,224,3)) # height, width, color_channels

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2,0,1) # shifts axis 0->1, 1->2, 2->0

print(f'Previous shape: {x_original.shape}')
print(f'New shape: {x_permuted.shape}')  # colour_channel, height, width

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [94]:
x_original

tensor([[[0.2971, 0.2104, 0.2237],
         [0.2855, 0.8040, 0.2371],
         [0.2659, 0.1217, 0.3877],
         ...,
         [0.9398, 0.9395, 0.3284],
         [0.3858, 0.5533, 0.1495],
         [0.3001, 0.7297, 0.7672]],

        [[0.6561, 0.1547, 0.8571],
         [0.4162, 0.8224, 0.7521],
         [0.2451, 0.3889, 0.3319],
         ...,
         [0.6996, 0.2326, 0.1175],
         [0.7899, 0.4512, 0.8447],
         [0.3771, 0.7290, 0.2998]],

        [[0.4581, 0.5118, 0.5146],
         [0.1405, 0.3973, 0.5485],
         [0.8166, 0.6657, 0.4521],
         ...,
         [0.1911, 0.5159, 0.7699],
         [0.9745, 0.5348, 0.3566],
         [0.2191, 0.6788, 0.6509]],

        ...,

        [[0.7146, 0.9919, 0.0857],
         [0.8300, 0.8110, 0.5281],
         [0.9985, 0.9445, 0.0931],
         ...,
         [0.9451, 0.2687, 0.6333],
         [0.6904, 0.1051, 0.0975],
         [0.3974, 0.7046, 0.2742]],

        [[0.5233, 0.4211, 0.5313],
         [0.4804, 0.8216, 0.8569],
         [0.

In [95]:
x_permuted

tensor([[[0.2971, 0.2855, 0.2659,  ..., 0.9398, 0.3858, 0.3001],
         [0.6561, 0.4162, 0.2451,  ..., 0.6996, 0.7899, 0.3771],
         [0.4581, 0.1405, 0.8166,  ..., 0.1911, 0.9745, 0.2191],
         ...,
         [0.7146, 0.8300, 0.9985,  ..., 0.9451, 0.6904, 0.3974],
         [0.5233, 0.4804, 0.5049,  ..., 0.4064, 0.2473, 0.3115],
         [0.3354, 0.8808, 0.0559,  ..., 0.7711, 0.2079, 0.3112]],

        [[0.2104, 0.8040, 0.1217,  ..., 0.9395, 0.5533, 0.7297],
         [0.1547, 0.8224, 0.3889,  ..., 0.2326, 0.4512, 0.7290],
         [0.5118, 0.3973, 0.6657,  ..., 0.5159, 0.5348, 0.6788],
         ...,
         [0.9919, 0.8110, 0.9445,  ..., 0.2687, 0.1051, 0.7046],
         [0.4211, 0.8216, 0.6274,  ..., 0.3929, 0.0450, 0.1402],
         [0.6826, 0.2732, 0.7243,  ..., 0.9239, 0.5407, 0.4501]],

        [[0.2237, 0.2371, 0.3877,  ..., 0.3284, 0.1495, 0.7672],
         [0.8571, 0.7521, 0.3319,  ..., 0.1175, 0.8447, 0.2998],
         [0.5146, 0.5485, 0.4521,  ..., 0.7699, 0.3566, 0.

In [97]:
x_original[0,0,0] = 72434343
x_original[0,0,0], x_permuted[0,0,0]

(tensor(72434344.), tensor(72434344.))

### Indexing with PyTorch is similar to indexing with NumPy.

In [98]:
# Create a tensor
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [99]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [100]:
# Let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [102]:
# Let's index on the most inner bracket (last dimension)
x[0][2][2]

tensor(9)

In [103]:
# You can also use ":" to select "all" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [104]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [105]:
# Get all values of the 0th dimension but only the 1 index value of 1st and 2nd dimesnion
x[:,1,1]

tensor([5])

In [106]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimensio
x[0,0,:]

tensor([1, 2, 3])

In [110]:
# Index on x to return 9
print(x[0][2][2])

# index on x to return 3,6,9
print(x[:,:,-1])

tensor(9)
tensor([[3, 6, 9]])


## PyTorch tensors & NumPy

NumPy is a popular scientific Python nummerical computing library.

And because of this, PyTorch hahs functionality to interact with it.

* Data is Numpy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor ->Numpy-> `torch.Tensor.numpy()`

In [111]:
# NumPy array to tensor
array= np.arange(1.0,8.)
tensor = torch.from_numpy(array)   # warning: when converting from numpy -> pytorch, pytorch relexts numpy's default dtype
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [114]:
# Change theh value of array, what will this do to `tensor`?
array = array +1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [115]:
# Tensor to p array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [116]:
# Change the tensor, what happens to `numpy_tensor`?
tensor = tensor +1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducbility (trying to take random out of random)

In short how a neural network learns:
`start with random numbers` -> tensor operatons -> update random numbers to try and make them better representations of the data -> again -> angain -> again...

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.
Essentially what the random seed does is 'flavor' the randomness.

In [117]:
# create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A==random_tensor_B)

tensor([[0.0252, 0.1422, 0.5692, 0.5167],
        [0.5081, 0.1480, 0.9136, 0.8561],
        [0.8801, 0.5568, 0.6583, 0.0235]])
tensor([[0.6993, 0.9372, 0.1089, 0.7880],
        [0.3007, 0.5925, 0.8197, 0.8035],
        [0.7321, 0.9269, 0.5969, 0.5432]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [118]:
# Let's make some random but reproducible tensors

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C==random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs ( and making faster computations)
GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky
dory (good).

### 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU (options to upgrade as well)
2. Use you own GPU - takes a little bit o setup and requires the investment of purchassing a GPU, there's lots of options...
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them.

For 2,3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refer to PyTorch setup documentation: https://pytorch.org/get-started/locally/

### 2. Check for GPU access with PyTorch

In [120]:
# check for GPU access with pyTorch
torch.cuda.is_available()

False

In [121]:
# Setup device agnostic code
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cpu'

In [122]:
# Count number of devices
torch.cuda.device_count()

0

## 3. Putting tensors  (and models) on theh GPU

The reason we wnant our tensors/models on the GPU is because using a GPU results in faster computations.

In [123]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1,2,3])

# Tensor not on GPU
print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [124]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])

### 4. Moving tensors back to the CPU

In [125]:
# If tensor is on GPU, can't transfor it to NumPy
tensor_on_gpu.numpy()

array([1, 2, 3], dtype=int64)

In [127]:
#  To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3], dtype=int64)

In [128]:
tensor_on_gpu

tensor([1, 2, 3])

In [ ]:
## 